//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Chernovik_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "наим as \'Наим\'"})]
    [View("ДолжностьL", new string[] {
            "наим as \'Наим\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private string fнаим;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// наим.
        /// </summary>
        // *** Start programmer edit section *** (Должность.наим CustomAttributes)

        // *** End programmer edit section *** (Должность.наим CustomAttributes)
        [StrLen(255)]
        public virtual string наим
        {
            get
            {
                // *** Start programmer edit section *** (Должность.наим Get start)

                // *** End programmer edit section *** (Должность.наим Get start)
                string result = this.fнаим;
                // *** Start programmer edit section *** (Должность.наим Get end)

                // *** End programmer edit section *** (Должность.наим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.наим Set start)

                // *** End programmer edit section *** (Должность.наим Set start)
                this.fнаим = value;
                // *** Start programmer edit section *** (Должность.наим Set end)

                // *** End programmer edit section *** (Должность.наим Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Chernovik_1.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Chernovik_1.Должность));
                }
            }
        }
    }
}
