//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Chernovik_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список.
    /// </summary>
    // *** Start programmer edit section *** (Список CustomAttributes)

    // *** End programmer edit section *** (Список CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокE", new string[] {
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("СписокE", "Списоккк", "СписокккE", true, "", "Списоккк", true, new string[] {
            ""})]
    [View("СписокL", new string[] {
            "Дата as \'Дата\'"})]
    public class Список : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Chernovik_1.DetailArrayOfСписоккк fСписоккк;
        
        // *** Start programmer edit section *** (Список CustomMembers)

        // *** End programmer edit section *** (Список CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Список.Дата CustomAttributes)

        // *** End programmer edit section *** (Список.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Список.Дата Get start)

                // *** End programmer edit section *** (Список.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Список.Дата Get end)

                // *** End programmer edit section *** (Список.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Список.Дата Set start)

                // *** End programmer edit section *** (Список.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Список.Дата Set end)

                // *** End programmer edit section *** (Список.Дата Set end)
            }
        }
        
        /// <summary>
        /// Список.
        /// </summary>
        // *** Start programmer edit section *** (Список.Списоккк CustomAttributes)

        // *** End programmer edit section *** (Список.Списоккк CustomAttributes)
        public virtual IIS.Chernovik_1.DetailArrayOfСписоккк Списоккк
        {
            get
            {
                // *** Start programmer edit section *** (Список.Списоккк Get start)

                // *** End programmer edit section *** (Список.Списоккк Get start)
                if ((this.fСписоккк == null))
                {
                    this.fСписоккк = new IIS.Chernovik_1.DetailArrayOfСписоккк(this);
                }
                IIS.Chernovik_1.DetailArrayOfСписоккк result = this.fСписоккк;
                // *** Start programmer edit section *** (Список.Списоккк Get end)

                // *** End programmer edit section *** (Список.Списоккк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Список.Списоккк Set start)

                // *** End programmer edit section *** (Список.Списоккк Set start)
                this.fСписоккк = value;
                // *** Start programmer edit section *** (Список.Списоккк Set end)

                // *** End programmer edit section *** (Список.Списоккк Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокE", typeof(IIS.Chernovik_1.Список));
                }
            }
            
            /// <summary>
            /// "СписокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокL", typeof(IIS.Chernovik_1.Список));
                }
            }
        }
    }
}
