//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Chernovik_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Списоккк.
    /// </summary>
    // *** Start programmer edit section *** (Списоккк CustomAttributes)

    // *** End programmer edit section *** (Списоккк CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокккE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Имя as \'Имя\'"}, Hidden=new string[] {
            "Сотрудники.Имя"})]
    [MasterViewDefineAttribute("СписокккE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    public class Списоккк : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Chernovik_1.Сотрудники fСотрудники;
        
        private IIS.Chernovik_1.Список fСписок;
        
        // *** Start programmer edit section *** (Списоккк CustomMembers)

        // *** End programmer edit section *** (Списоккк CustomMembers)

        
        /// <summary>
        /// Списоккк.
        /// </summary>
        // *** Start programmer edit section *** (Списоккк.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Списоккк.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Chernovik_1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Списоккк.Сотрудники Get start)

                // *** End programmer edit section *** (Списоккк.Сотрудники Get start)
                IIS.Chernovik_1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Списоккк.Сотрудники Get end)

                // *** End programmer edit section *** (Списоккк.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Списоккк.Сотрудники Set start)

                // *** End programmer edit section *** (Списоккк.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Списоккк.Сотрудники Set end)

                // *** End programmer edit section *** (Списоккк.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Chernovik_1.Список.
        /// </summary>
        // *** Start programmer edit section *** (Списоккк.Список CustomAttributes)

        // *** End programmer edit section *** (Списоккк.Список CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Список"})]
        public virtual IIS.Chernovik_1.Список Список
        {
            get
            {
                // *** Start programmer edit section *** (Списоккк.Список Get start)

                // *** End programmer edit section *** (Списоккк.Список Get start)
                IIS.Chernovik_1.Список result = this.fСписок;
                // *** Start programmer edit section *** (Списоккк.Список Get end)

                // *** End programmer edit section *** (Списоккк.Список Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Списоккк.Список Set start)

                // *** End programmer edit section *** (Списоккк.Список Set start)
                this.fСписок = value;
                // *** Start programmer edit section *** (Списоккк.Список Set end)

                // *** End programmer edit section *** (Списоккк.Список Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокккE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокккE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокккE", typeof(IIS.Chernovik_1.Списоккк));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Списоккк.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСписоккк CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСписоккк CustomAttributes)
    public class DetailArrayOfСписоккк : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Chernovik_1.DetailArrayOfСписоккк members)

        // *** End programmer edit section *** (IIS.Chernovik_1.DetailArrayOfСписоккк members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Списоккк by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Списоккк.
        /// </summary>
        public DetailArrayOfСписоккк(IIS.Chernovik_1.Список fСписок) : 
                base(typeof(Списоккк), ((ICSSoft.STORMNET.DataObject)(fСписок)))
        {
        }
        
        public IIS.Chernovik_1.Списоккк this[int index]
        {
            get
            {
                return ((IIS.Chernovik_1.Списоккк)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Chernovik_1.Списоккк dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
